#ifndef ICON_DEFAULT_H
#define ICON_DEFAULT_H

// Generated by tools/bitmap_2_c_array_converter.py
//   -i resources/icons/default.png
//   -o src/menu/icons/icon_default.h
//   -t 0.5
//   -g 4
//   -s None

#include <stdint.h>
#include <avr/pgmspace.h>

#define ICON_DEFAULT_Y_LEN      2
#define ICON_DEFAULT_X_LEN      16
#define ICON_DEFAULT_ARRAY_LEN  32

const PROGMEM uint8_t _icon_default[32] = {
	0x00, 0x00, 0x00, 0xC0, 
	0x20, 0x10, 0x48, 0x28, 
	0x08, 0x08, 0x10, 0x20, 
	0xC0, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x03, 
	0x04, 0x08, 0x10, 0x10, 
	0x10, 0x10, 0x08, 0x04, 
	0x03, 0x00, 0x00, 0x00, 
};

#endif // ICON_DEFAULT_H
